import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  root: '.',
  base: './',
  resolve: {
    alias: {
      '../../api/client': path.resolve(__dirname, '../../apps/web/src/api/client.ts'),
      '../api/client': path.resolve(__dirname, '../../apps/web/src/api/client.ts'),
      '../../api/companions': path.resolve(__dirname, '../../apps/web/src/api/companions.ts'),
      '../../api/customers': path.resolve(__dirname, '../../apps/web/src/api/customers.ts'),
      '../../api/orders': path.resolve(__dirname, '../../apps/web/src/api/orders.ts'),
      '../../api/billing': path.resolve(__dirname, '../../apps/web/src/api/billing.ts'),
      '../../api/config': path.resolve(__dirname, '../../apps/web/src/api/config.ts'),
      '../../api/expenses': path.resolve(__dirname, '../../apps/web/src/api/expenses.ts'),
      '../../api/studios': path.resolve(__dirname, '../../apps/web/src/api/studios.ts'),
      '../../api/employees': path.resolve(__dirname, '../../apps/web/src/api/employees.ts'),
      '../../api/dashboard': path.resolve(__dirname, '../../apps/web/src/api/dashboard.ts'),
      '../../api/ai': path.resolve(__dirname, '../../apps/web/src/api/ai.ts'),
      '../../api/blacklist': path.resolve(__dirname, '../../apps/web/src/api/blacklist.ts'),
      '../../stores/authStore': path.resolve(__dirname, '../../apps/web/src/stores/authStore.ts'),
      '../../constants': path.resolve(__dirname, '../../apps/web/src/constants/index.ts'),
      '../../constants/orders': path.resolve(__dirname, '../../apps/web/src/constants/orders.ts'),
      '../../components/ChatModal': path.resolve(__dirname, '../../apps/web/src/components/ChatModal.tsx'),
      '../../components/CreateOrderModal': path.resolve(__dirname, '../../apps/web/src/components/CreateOrderModal.tsx'),
      '../../components/OrderTable': path.resolve(__dirname, '../../apps/web/src/components/OrderTable.tsx'),
      '../../components/StatusBlacklistConfigModal': path.resolve(__dirname, '../../apps/web/src/components/StatusBlacklistConfigModal.tsx'),
      // Chat 3.0
      '../../components/chat': path.resolve(__dirname, '../../apps/web/src/components/chat'),
      '../../components/chat/ChatPanel': path.resolve(__dirname, '../../apps/web/src/components/chat/ChatPanel.tsx'),
      '../../components/chat/MessageList': path.resolve(__dirname, '../../apps/web/src/components/chat/MessageList.tsx'),
      '../../components/chat/MessageBubble': path.resolve(__dirname, '../../apps/web/src/components/chat/MessageBubble.tsx'),
      '../../components/chat/ChatComposer': path.resolve(__dirname, '../../apps/web/src/components/chat/ChatComposer.tsx'),
      '../../components/chat/ChatHeader': path.resolve(__dirname, '../../apps/web/src/components/chat/ChatHeader.tsx'),
      '../../components/chat/MessageContextMenu': path.resolve(__dirname, '../../apps/web/src/components/chat/MessageContextMenu.tsx'),
      '../../components/chat/MessageReactions': path.resolve(__dirname, '../../apps/web/src/components/chat/MessageReactions.tsx'),
      '../../components/chat/ReplyBar': path.resolve(__dirname, '../../apps/web/src/components/chat/ReplyBar.tsx'),
      '../../components/chat/ReplyPreview': path.resolve(__dirname, '../../apps/web/src/components/chat/ReplyPreview.tsx'),
      '../../components/chat/DateDivider': path.resolve(__dirname, '../../apps/web/src/components/chat/DateDivider.tsx'),
      '../../components/chat/TypingIndicator': path.resolve(__dirname, '../../apps/web/src/components/chat/TypingIndicator.tsx'),
      '../../components/chat/FileMessage': path.resolve(__dirname, '../../apps/web/src/components/chat/FileMessage.tsx'),
      '../../components/chat/OrderCardMessage': path.resolve(__dirname, '../../apps/web/src/components/chat/OrderCardMessage.tsx'),
      '../../components/chat/ImageViewer': path.resolve(__dirname, '../../apps/web/src/components/chat/ImageViewer.tsx'),
      '../../components/chat/EmbeddedChatPanel': path.resolve(__dirname, '../../apps/web/src/components/chat/EmbeddedChatPanel.tsx'),
      '../../components/chat/ChatProvider': path.resolve(__dirname, '../../apps/web/src/components/chat/ChatProvider.tsx'),
      '../../components/chat/CompanionSidebar': path.resolve(__dirname, '../../apps/web/src/components/chat/CompanionSidebar.tsx'),
      '../../components/chat/CompanionItem': path.resolve(__dirname, '../../apps/web/src/components/chat/CompanionItem.tsx'),
      '../../stores/chatStore': path.resolve(__dirname, '../../apps/web/src/stores/chatStore.ts'),
      '../../api/chat': path.resolve(__dirname, '../../apps/web/src/api/chat.ts'),
      '../../hooks/useSocket': path.resolve(__dirname, '../../apps/web/src/hooks/useSocket.ts'),
      '../../hooks/useChatSync': path.resolve(__dirname, '../../apps/web/src/hooks/useChatSync.ts'),
      '../../hooks/useChatNotification': path.resolve(__dirname, '../../apps/web/src/hooks/useChatNotification.ts'),
      '../../hooks/useVirtualScroll': path.resolve(__dirname, '../../apps/web/src/hooks/useVirtualScroll.ts'),
      '../../workers/chat-db': path.resolve(__dirname, '../../apps/web/src/workers/chat-db.ts'),
      '../../utils/notificationSound': path.resolve(__dirname, '../../apps/web/src/utils/notificationSound.ts'),
      '../../components/ConversationList': path.resolve(__dirname, '../../apps/web/src/components/ConversationList.tsx'),
      '../../components/FloatingChatWidget': path.resolve(__dirname, '../../apps/web/src/components/FloatingChatWidget.tsx'),
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
  },
  server: {
    port: 5174,
  },
});
