ALTER TABLE "Order" ADD COLUMN "refundedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN "refundReason" TEXT;
ALTER TABLE "Order" ADD COLUMN "depositedAt" TIMESTAMP(3);
ALTER TABLE "Order" ADD COLUMN "depositAmount" DOUBLE PRECISION;

